version: '3.1'

services:

  uzwarcom-db:
    image: bitnami/mariadb:10.5.12
    ports:
      - "3310:3310"
    environment:
      - MARIADB_AUTHENTICATION_PLUGIN=mysql_native_password
      - MARIADB_DATABASE=uzwarcom
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PORT_NUMBER=3310

